import * as XLSX from 'xlsx';

/**
 * Exports an analytics working paper to a 3-tab Excel workbook.
 *
 * Tabs:
 * 1. Raw Data — full uploaded file as-is
 * 2. Exceptions — rows that triggered the test
 * 3. Working Paper — test metadata, results summary, auditor conclusion + notes
 */
export function exportAnalyticsToExcel({ test, headers, allRows, exceptionRows, exceptionCount, totalRows, conclusion, notes, auditeeDetails }) {
  const wb = XLSX.utils.book_new();
  const date = new Date().toISOString().split('T')[0];

  // ---------------------------------------------------------------------------
  // Tab 1: Raw Data
  // ---------------------------------------------------------------------------
  const rawData = [headers, ...allRows];
  const wsRaw = XLSX.utils.aoa_to_sheet(rawData);
  // Set column widths
  wsRaw['!cols'] = headers.map(() => ({ wch: 20 }));
  XLSX.utils.book_append_sheet(wb, wsRaw, 'Raw Data');

  // ---------------------------------------------------------------------------
  // Tab 2: Exceptions
  // ---------------------------------------------------------------------------
  const excData = [headers, ...exceptionRows];
  const wsExc = XLSX.utils.aoa_to_sheet(excData);
  wsExc['!cols'] = headers.map(() => ({ wch: 20 }));
  XLSX.utils.book_append_sheet(wb, wsExc, 'Exceptions');

  // ---------------------------------------------------------------------------
  // Tab 3: Working Paper
  // ---------------------------------------------------------------------------
  const clientName = auditeeDetails?.clientName || '';
  const engagementRef = auditeeDetails?.engagementRef || '';
  const auditorName = auditeeDetails?.auditorName || '';
  const periodFrom = auditeeDetails?.periodFrom || '';
  const periodTo = auditeeDetails?.periodTo || '';

  const wpRows = [
    ['ANALYTICS WORKING PAPER', ''],
    [''],
    ['Client', clientName],
    ['Engagement Reference', engagementRef],
    ['Prepared by', auditorName],
    ['Period', periodFrom && periodTo ? `${periodFrom} to ${periodTo}` : periodFrom || periodTo || ''],
    ['Date Exported', date],
    [''],
    ['TEST DETAILS', ''],
    ['Test ID', test.id],
    ['Test Name', test.name],
    ['Purpose', test.purpose],
    ['Data Tested', test.dataneeded],
    [''],
    ['RESULTS SUMMARY', ''],
    ['Total Records Tested', totalRows],
    ['Exceptions Found', exceptionCount],
    ['Exception Rate', totalRows > 0 ? `${((exceptionCount / totalRows) * 100).toFixed(1)}%` : '0.0%'],
    [''],
    ['AUDITOR CONCLUSION', ''],
    ['Conclusion', conclusion || ''],
    [''],
    ['NOTES', ''],
    ['Notes', notes || ''],
    [''],
    ['RED FLAGS TO CONSIDER', ''],
    [test.redflags],
    [''],
    ['AI Disclosure', 'Results generated by Verifai analytics engine. No AI was used in the data filtering logic. Auditor conclusions are the responsibility of the preparer.'],
  ];

  const wsWP = XLSX.utils.aoa_to_sheet(wpRows);
  wsWP['!cols'] = [{ wch: 28 }, { wch: 70 }];

  // Bold the section headers
  const boldRows = [0, 8, 14, 18, 21, 24, 27];
  boldRows.forEach(r => {
    const cellRef = XLSX.utils.encode_cell({ r, c: 0 });
    if (wsWP[cellRef]) {
      wsWP[cellRef].s = { font: { bold: true } };
    }
  });

  XLSX.utils.book_append_sheet(wb, wsWP, 'Working Paper');

  // ---------------------------------------------------------------------------
  // Download
  // ---------------------------------------------------------------------------
  const filename = `Analytics_${test.id}_${clientName.replace(/\s+/g, '_') || 'WorkingPaper'}_${date}.xlsx`;
  XLSX.writeFile(wb, filename);
}
