import * as XLSX from 'xlsx';

/**
 * Exports a process walkthrough working paper to an Excel workbook.
 *
 * Sheet layout:
 * - "Summary" tab: engagement details, process overview, scope, objectives, overall conclusion
 * - "Walkthrough" tab: per checkpoint — Area / Expected / Described / Design Adequacy / Notes
 * - "Freeform Notes" tab: open notes, date, auditor name
 */
export function exportWalkthroughToExcel(walkthrough, auditeeDetails) {
  if (!walkthrough) return;

  const workbook = XLSX.utils.book_new();
  const date = new Date().toISOString().split('T')[0];

  // ---------------------------------------------------------------------------
  // Helper: add a worksheet with column widths
  // ---------------------------------------------------------------------------
  function makeSheet(rows, colWidths) {
    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws['!cols'] = colWidths.map(w => ({ wch: w }));
    return ws;
  }

  // ---------------------------------------------------------------------------
  // Tab 1: Summary
  // ---------------------------------------------------------------------------
  const summaryRows = [];

  summaryRows.push(['PROCESS WALKTHROUGH WORKING PAPER']);
  summaryRows.push([walkthrough.walkthroughTitle || '']);
  summaryRows.push(['']);

  if (auditeeDetails) {
    if (auditeeDetails.clientName)       summaryRows.push(['Client:', auditeeDetails.clientName]);
    if (auditeeDetails.department)       summaryRows.push(['Department:', auditeeDetails.department]);
    if (auditeeDetails.engagementRef)    summaryRows.push(['Engagement Ref:', auditeeDetails.engagementRef]);
    if (auditeeDetails.auditorName)      summaryRows.push(['Auditor:', auditeeDetails.auditorName]);
    if (auditeeDetails.primaryContactName) summaryRows.push(['Primary Contact:', `${auditeeDetails.primaryContactName}${auditeeDetails.primaryContactTitle ? ` — ${auditeeDetails.primaryContactTitle}` : ''}`]);
    if (auditeeDetails.periodFrom || auditeeDetails.periodTo) {
      summaryRows.push(['Audit Period:', `${auditeeDetails.periodFrom || ''} to ${auditeeDetails.periodTo || ''}`]);
    }
    summaryRows.push(['Export Date:', date]);
    summaryRows.push(['']);
  }

  summaryRows.push(['PROCESS OVERVIEW']);
  summaryRows.push([walkthrough.processOverview || '']);
  summaryRows.push(['']);

  summaryRows.push(['SCOPE']);
  summaryRows.push([walkthrough.scope || '']);
  summaryRows.push(['']);

  summaryRows.push(['OBJECTIVES']);
  (walkthrough.objectives || []).forEach((obj, i) => {
    summaryRows.push([`${i + 1}.`, obj]);
  });
  summaryRows.push(['']);

  summaryRows.push(['OVERALL CONCLUSION']);
  summaryRows.push([walkthrough.overallConclusion || '']);
  summaryRows.push(['']);

  summaryRows.push(['Generated by Verifai — AI-assisted content. Reviewed and completed by auditor. All content should be verified before use.']);

  const summarySheet = makeSheet(summaryRows, [30, 100]);
  XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

  // ---------------------------------------------------------------------------
  // Tab 2: Walkthrough (per checkpoint working paper grid)
  // ---------------------------------------------------------------------------
  const walkthroughRows = [];

  walkthroughRows.push([
    'ID',
    'Area',
    'Expected State (AI)',
    'Design Considerations (AI)',
    'What Was Described',
    'Design Adequacy',
    'Notes',
  ]);

  (walkthrough.checkpoints || []).forEach(cp => {
    walkthroughRows.push([
      cp.id || '',
      cp.area || '',
      cp.expected || '',
      cp.designConsiderations || '',
      cp.described || '',
      cp.designAdequacy || 'Not Assessed',
      cp.notes || '',
    ]);
  });

  walkthroughRows.push(['']);
  walkthroughRows.push(['Generated by Verifai — AI-assisted content. Reviewed and completed by auditor. All content should be verified before use.']);

  const walkthroughSheet = makeSheet(walkthroughRows, [8, 30, 55, 50, 55, 18, 45]);

  // Enable text wrapping
  const walkthroughRange = XLSX.utils.decode_range(walkthroughSheet['!ref'] || 'A1');
  for (let R = walkthroughRange.s.r; R <= walkthroughRange.e.r; R++) {
    for (let C = walkthroughRange.s.c; C <= walkthroughRange.e.c; C++) {
      const cellAddr = XLSX.utils.encode_cell({ r: R, c: C });
      if (!walkthroughSheet[cellAddr]) continue;
      if (!walkthroughSheet[cellAddr].s) walkthroughSheet[cellAddr].s = {};
      walkthroughSheet[cellAddr].s.alignment = { wrapText: true, vertical: 'top' };
    }
  }

  XLSX.utils.book_append_sheet(workbook, walkthroughSheet, 'Walkthrough');

  // ---------------------------------------------------------------------------
  // Tab 3: Freeform Notes
  // ---------------------------------------------------------------------------
  const freeformRows = [];

  freeformRows.push(['ADDITIONAL NOTES FROM INTERVIEWS']);
  freeformRows.push(['']);

  if (auditeeDetails?.auditorName) freeformRows.push(['Auditor:', auditeeDetails.auditorName]);
  freeformRows.push(['Date:', date]);
  freeformRows.push(['']);

  freeformRows.push(['Notes:']);
  freeformRows.push([walkthrough.freeformNotes || '']);
  freeformRows.push(['']);

  freeformRows.push(['Generated by Verifai — AI-assisted content. Reviewed and completed by auditor. All content should be verified before use.']);

  const freeformSheet = makeSheet(freeformRows, [20, 100]);
  XLSX.utils.book_append_sheet(workbook, freeformSheet, 'Freeform Notes');

  // ---------------------------------------------------------------------------
  // Write file
  // ---------------------------------------------------------------------------
  const processSlug = (walkthrough.walkthroughTitle || 'Walkthrough').replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40);
  const fileName = `${processSlug}_${date}.xlsx`;
  XLSX.writeFile(workbook, fileName);
}
