import * as XLSX from 'xlsx';

/**
 * Exports an analytics working paper to a 3-tab Excel workbook.
 *
 * Tabs:
 * 1. Raw Data       — full uploaded file as-is
 * 2. Exceptions     — rows that triggered the test
 * 3. {test.id}      — working paper: engagement details, methodology, results, audit work done, conclusion
 */
export function exportAnalyticsToExcel({ test, headers, allRows, exceptionRows, exceptionCount, totalRows, conclusion, workDone, auditeeDetails }) {
  const wb = XLSX.utils.book_new();
  const date = new Date().toISOString().split('T')[0];

  // ---------------------------------------------------------------------------
  // Tab 1: Raw Data
  // ---------------------------------------------------------------------------
  const wsRaw = XLSX.utils.aoa_to_sheet([headers, ...allRows]);
  wsRaw['!cols'] = headers.map(() => ({ wch: 20 }));
  XLSX.utils.book_append_sheet(wb, wsRaw, 'Raw Data');

  // ---------------------------------------------------------------------------
  // Tab 2: Exceptions
  // ---------------------------------------------------------------------------
  const wsExc = XLSX.utils.aoa_to_sheet([headers, ...exceptionRows]);
  wsExc['!cols'] = headers.map(() => ({ wch: 20 }));
  XLSX.utils.book_append_sheet(wb, wsExc, 'Exceptions');

  // ---------------------------------------------------------------------------
  // Tab 3: Working Paper (named after test ID)
  // ---------------------------------------------------------------------------
  const clientName   = auditeeDetails?.clientName    || '';
  const engRef       = auditeeDetails?.engagementRef || '';
  const auditorName  = auditeeDetails?.auditorName   || '';
  const periodFrom   = auditeeDetails?.periodFrom    || '';
  const periodTo     = auditeeDetails?.periodTo      || '';
  const period       = periodFrom && periodTo ? `${periodFrom} to ${periodTo}` : periodFrom || periodTo || '';

  const methodologyRows = (test.steps || []).map((step, i) => [`  ${i + 1}.`, step]);

  const wpRows = [
    ['ANALYTICS WORKING PAPER', ''],
    [''],
    ['Client',                clientName],
    ['Engagement Reference',  engRef],
    ['Prepared by',           auditorName],
    ['Period',                period],
    ['Date Exported',         date],
    [''],
    ['TEST DETAILS', ''],
    ['Test ID',               test.id],
    ['Test Name',             test.name],
    ['Purpose',               test.purpose],
    ['Data Tested',           test.dataneeded],
    [''],
    ['METHODOLOGY', ''],
    ['The following steps were performed. A reviewer can manually reperform this test using these steps.', ''],
    ...methodologyRows,
    [''],
    ['Red Flags Considered',  test.redflags],
    [''],
    ['RESULTS SUMMARY', ''],
    ['Total Records Tested',  totalRows],
    ['Exceptions Found',      exceptionCount],
    ['Exception Rate',        totalRows > 0 ? `${((exceptionCount / totalRows) * 100).toFixed(1)}%` : '0.0%'],
    [''],
    ['AUDIT WORK DONE', ''],
    ['', workDone || ''],
    [''],
    ['CONCLUSION', ''],
    ['', conclusion || ''],
    [''],
    ['AI Disclosure', 'Results generated by the Verifai analytics engine. No AI was used in the data filtering logic. All audit judgements and conclusions are the responsibility of the preparer.'],
  ];

  const wsWP = XLSX.utils.aoa_to_sheet(wpRows);
  wsWP['!cols'] = [{ wch: 30 }, { wch: 80 }];

  XLSX.utils.book_append_sheet(wb, wsWP, test.id);

  // ---------------------------------------------------------------------------
  // Download
  // ---------------------------------------------------------------------------
  const filename = `Analytics_${test.id}_${clientName.replace(/\s+/g, '_') || 'WorkingPaper'}_${date}.xlsx`;
  XLSX.writeFile(wb, filename);
}
