import {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, BorderStyle
} from 'docx';

const COLORS = {
  headerBg: '1E3A5F',
  adequate: '27AE60',
  inadequate: 'C0392B',
  notAssessed: '95A5A6',
};

function adequacyColor(rating) {
  if (!rating) return COLORS.notAssessed;
  const r = rating.toLowerCase();
  if (r.includes('inadequate')) return COLORS.inadequate;
  if (r.includes('adequate')) return COLORS.adequate;
  return COLORS.notAssessed;
}

function bold(text, size = 22) {
  return new TextRun({ text: String(text || ''), bold: true, size });
}

function normal(text, size = 22) {
  return new TextRun({ text: String(text || ''), size });
}

function labeledPara(label, value) {
  if (!value) return null;
  return new Paragraph({ children: [bold(label + ': '), normal(value)], spacing: { after: 100 } });
}

function sectionHeading(text) {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 100 } });
}

function bodyPara(text) {
  return new Paragraph({ children: [normal(text || '—')], spacing: { after: 120 } });
}

function divider() {
  return new Paragraph({
    border: { bottom: { color: 'CCCCCC', size: 1, style: BorderStyle.SINGLE } },
    spacing: { before: 200, after: 200 },
  });
}

export async function exportWalkthroughToWord(walkthrough, auditeeDetails) {
  if (!walkthrough) return;

  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
  const children = [];

  // Cover
  children.push(
    new Paragraph({ children: [new TextRun({ text: 'PROCESS WALKTHROUGH WORKING PAPER', bold: true, size: 32, color: COLORS.headerBg })], spacing: { after: 80 } }),
    new Paragraph({ children: [bold(walkthrough.walkthroughTitle || '', 26)], spacing: { after: 200 } }),
  );

  if (auditeeDetails) {
    const details = [
      ['Client', auditeeDetails.clientName],
      ['Department', auditeeDetails.department],
      ['Engagement Ref', auditeeDetails.engagementRef],
      ['Auditor', auditeeDetails.auditorName],
      ['Primary Contact', auditeeDetails.primaryContactName ? `${auditeeDetails.primaryContactName}${auditeeDetails.primaryContactTitle ? ` — ${auditeeDetails.primaryContactTitle}` : ''}` : null],
      ['Audit Period', (auditeeDetails.periodFrom || auditeeDetails.periodTo) ? `${auditeeDetails.periodFrom || ''} to ${auditeeDetails.periodTo || ''}` : null],
      ['Export Date', date],
    ];
    details.forEach(([label, value]) => { if (value) children.push(labeledPara(label, value)); });
  } else {
    children.push(labeledPara('Export Date', date));
  }

  children.push(divider());

  if (walkthrough.processOverview) { children.push(sectionHeading('Process Overview')); children.push(bodyPara(walkthrough.processOverview)); }
  if (walkthrough.scope) { children.push(sectionHeading('Scope')); children.push(bodyPara(walkthrough.scope)); }
  if (walkthrough.objectives?.length) {
    children.push(sectionHeading('Objectives'));
    walkthrough.objectives.forEach((obj, i) => children.push(new Paragraph({ children: [normal(`${i + 1}. ${obj}`)], spacing: { after: 80 } })));
  }

  children.push(divider());
  children.push(new Paragraph({ text: 'Walkthrough Findings', heading: HeadingLevel.HEADING_1, spacing: { before: 200, after: 150 } }));

  (walkthrough.checkpoints || []).forEach((cp, idx) => {
    children.push(new Paragraph({ children: [bold(`${cp.id ? cp.id + ' — ' : ''}${cp.area || `Checkpoint ${idx + 1}`}`, 24)], spacing: { before: 250, after: 80 } }));
    if (cp.expected) children.push(new Paragraph({ children: [bold('Expected State: '), normal(cp.expected)], spacing: { after: 80 } }));
    if (cp.designConsiderations) children.push(new Paragraph({ children: [bold('Design Considerations: '), normal(cp.designConsiderations)], spacing: { after: 80 } }));
    children.push(new Paragraph({ children: [bold('Observed: '), normal(cp.described || '—')], spacing: { after: 80 } }));
    const rating = cp.designAdequacy || 'Not Assessed';
    children.push(new Paragraph({ children: [bold('Design Adequacy: '), new TextRun({ text: rating, bold: true, color: adequacyColor(rating), size: 22 })], spacing: { after: 80 } }));
    if (cp.notes) children.push(new Paragraph({ children: [bold('Notes: '), normal(cp.notes)], spacing: { after: 80 } }));
  });

  children.push(divider());
  if (walkthrough.overallConclusion) { children.push(sectionHeading('Overall Conclusion')); children.push(bodyPara(walkthrough.overallConclusion)); }
  if (walkthrough.freeformNotes) { children.push(sectionHeading('Additional Notes')); children.push(bodyPara(walkthrough.freeformNotes)); }

  children.push(divider());
  children.push(new Paragraph({ children: [new TextRun({ text: 'Generated by Verifai — AI-assisted content. Reviewed and completed by auditor. All content should be verified before use.', italics: true, size: 18, color: '888888' })], spacing: { before: 100 } }));

  const doc = new Document({ sections: [{ properties: {}, children }] });
  const blob = await Packer.toBlob(doc);
  const clientName = auditeeDetails?.clientName || 'Client';
  const processName = walkthrough.walkthroughTitle || 'Walkthrough';
  const filename = `${clientName} — ${processName} Walkthrough.docx`;
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
